### ISSUE TITLE
[🙏] Add snyk as dev dependency

### ISSUE THREAD

**Issue by wheresrhys** [snyk/cli#1231]
- `Language / Project Type:` js
- `Package Manager / Build Tool:` n/a

**Describe the user need**
It seems that adding snyk as a prod dependency is deliberate:
```
Adding Snyk to production dependencies (used by snyk protect)
```
This feels wrong for most (?all) projects as snyk will typically be used in the install/build phase. What's the rationale for not having it as a dev dependency?

**Describe expected behaviour**

Add as a dev dependency

**Comment by lili2311** [comment]
This article explains why [Snyk is a production dependency](https://support.snyk.io/hc/en-us/articles/360000911277-Why-has-Snyk-been-added-as-a-dependency-in-my-project-). I hope this answers your question?

**Comment by wheresrhys** [comment]
Thanks Lili - it doesn't explain why it's a _production_ dependency though. Unless there's some subtle detail I'm missing, or that isn't covered in the article,  all the required behaviour could be achieved by adding snyk as a development dependency.

**Comment by wheresrhys** [comment]
Does snyk patch work by copying its patches into node_modules or by referencing patches that are within `node_modules/snyk`? If the latter, I can see that snyk would need to be a prod dependency, but if the former I don't see the need for projects which are not packages that others may install.

To give an idea of my motivation for caring about this, AWS lambda imposes fairly tight limits on the size of the code you can deploy, and snyk + dependencies is quite big, so would like to keep it a dev dependency if possible.

**Comment by lili2311** [comment]
Snyk applies patches *after* the `npm i` step has finished by fetching the relevant patches referenced in `.snyk` file, locating the needed package on disk in `node_modules` and applying the patch directly to the code there. Every time `npm i` is run patches have to be re-applied as the original package code is fetched which is un-patched & vulnerable.

**Comment by lili2311** [comment]
@wheresrhys does the above answer your request? Can this issue be closed?

**Comment by benbucksch** [comment]
I've just installed a package that - for whatever reason - has `snyk` as dependency (not dev dependency). `snyk` in turn depends on a **huge** amount of other packages. Literally **hundreds**.

```
$ cat yarn.lock | wc -l
4751
$ git diff yarn.lock | wc -l
4053
$ git diff yarn.lock |grep "\+.*version"|wc -l
436
```

That is utterly ridiculous and completely prohibitive. I have to either not use the package that depends on snyk, or I have to fork it and modify it to remove snyk. Under no circumstance will I use a module that drags in hundreds and hundreds of other packages, unless that is really core and central to what my app does, and there's no other way to it.

**Comment by benbucksch** [comment]
So, indeed I traces this down to a commit that [your bot made](https://github.com/kengz/spacy-nlp/commit/4c9b17f6c0060c26ff68dde41f6b07207fd7a50c
). Using a bot to fix vulnerabilities in the soure code is a good idea. Doing that for every download and install is a bad idea. I read and understood [why Snyk is a production dependency](https://support.snyk.io/hc/en-us/articles/360000911277-Why-has-Snyk-been-added-as-a-dependency-in-my-project-), but I still disagree.

You write:
"we can't just fork the repository (we'd have to begin maintaining them). ...
When ... we have a patch that can be applied, we add snyk in as a dependency that also needs to run after your packages are installed to apply the patch post-install."

This is strictly untrue. If you can automatically (!) apply patches on my machine without causing breakage, then you can also fork the vulnerable project, automatically (!) apply the patches, and automatically keep current with the upstream project. In other words, instead of patching the source on my machine after install, you take upstream, patch it, and make that fork the dependency.

You may not like that idea, and maybe you have an even better solution. Whatever the solution is, the current one doesn't work. The solution you chose here is simply prohibitive. You cannot add hundreds of dependencies to tons of third party projects that have nothing to do with security. And the projects that include them will also get all of these deps. It makes the use of any of the libraries that you fixed practically impossible. Whatever you do, the current solution is not an option. Please find a better solution.

**Comment by lili2311** [comment]
Hi @benbucksch we work with maintainers where possible to make sure the patches become part of the released package versions, however sometimes this is simply not possible if the package is no longer maintained for example. 

Some packages may have a chain of updates that would need to occur by different maintainers to allow a latest version to be used (think something like lodash that is used by almost every package). As you can imagine maintaining a fork of millions of packages and propagating upgrades to them is incredibly difficult.

We are looking at future options where the snyk portion of the library that applies patched can be smaller & standalone to reduce the size of the bundle. 

In the mean time if you do not want to have your dependencies patched from vulnerabilities you can disable this in your settings by going to https://app.snyk.io/org/YOUR_ORG/manage/integrations/github and unticking the checkbox `include patches to vulnerable dependencies` this will remove patches from automatic Fix Prs.

<img width="855" alt="Screen Shot 2020-07-03 at 10 04 22" src="https://user-images.githubusercontent.com/2911613/86452724-a1d04d00-bd14-11ea-881a-ccb61587e298.png">


We have more documentation on the matter that I can recommend:
- https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities
- https://support.snyk.io/hc/en-us/articles/360004032437-Snyk-patches-to-fix

**Comment by benbucksch** [comment]
> we work with maintainers

In this case that affects me, I have not seen any such attempts.

Even if that was the case, the chosen solution here is simply a no-go. Letting every user every time download hundreds (!) of packages, just to apply a single patch, is wasteful to an extent that makes me speechless that this was even seriously considered.

> you can disable this in your settings

That doesn't work. The problem is that a simple `yarn add someotherlibrary` already drags in everything. I don't control someotherlibrary, I just want to use it. Or maybe it's just that someotherlibrary is using yetanotherlibrary that has caught the snyk bug.

This isn't a problem you can explain away. It's here. I had to fork a third party library, just because of this bug. :-(

**Comment by wheresrhys** [comment]
Sorry for my silence, but I think @benbucksch gives good expression to the worrying downsides of this behaviour that I'm motivated by - forcing installing a (in spirit, if not quite in practice) dev dependency with a massive dependency tree as a production dependency feels like a suboptimal solution, and maybe there are alternative approaches that could work.

As an additional point - `snyk protect` can be extremely slow; it takes npm's install times back to the bad old days of npm@2. By encouraging it to be a dependency of packages you will inevitably have the effect of having npm installs slow down for many nodejs users, even those who are not your direct customers. I'd think very carefully about that - it's not great PR for a company that otherwise has a great mission.

**Comment by lili2311** [comment]
Related: https://github.com/snyk/snyk/issues/1180

**Comment by lili2311** [comment]
Related https://github.com/snyk/snyk/issues/146

**Comment by benbucksch** [comment]
Please see https://github.com/snyk/snyk/issues/1231#issuecomment-653329090 , which shows an alternate solution that
a) you can script completely
b) avoids both the dependency and the devdependency (but changes the dependency reference for the vulnerable lib), and runs no additional code on dev or user machines
c) works seamlessly with CI

-- 
Sent from my cell phone. Please excuse the brevity. Please reply to ben.bucksch beonex.com

**Comment by JackuB** [comment]
Snyk protect command was removed from the Snyk CLI and was replaced by a smaller and faster approach. More details in the product announcements: https://updates.snyk.io/snyk-wizard-and-snyk-protect-removal-224137

As for the dev/dependency discussion:
- we don't recommend adding `snyk` package as a dependency to your projects
- for patches/protect, you can use much smaller and faster package, linked in the announcement above
- running commands with `npx` is also an option
